name: mobileapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: 0.257.0 # Matches your React icon set
  google_fonts: ^6.1.0
  url_launcher: ^6.1.11
  glassmorphism: ^3.0.0 # Optional helper, but I used native BackdropFilter below for control
  
    
  
  # --- Dependencies ---
  shared_preferences: ^2.2.2
  http: ^1.2.0
  provider: ^6.1.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  pinput: ^4.0.0 
  cupertino_icons: ^1.0.2

  
  # Add this line to fix the error:
  image_picker: ^1.0.7 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/