name: mobileapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  lottie: ^3.1.2             
  flutter_animate: ^4.5.0
  
  # Icons
  font_awesome_flutter: ^10.7.0 

  # API & State
  http: ^1.2.1               
  provider: ^6.1.2
  
  # Widgets
  pinput: ^5.0.0
  
  # Image Picking (New)
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/